language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: COMPOSER_FLAGS="--dev"
        - php: 7.2
          env: COMPOSER_FLAGS="--dev --ignore-platform-reqs" SYMFONY_DEPRECATIONS_HELPER=weak
        - php: nightly
          env: COMPOSER_FLAGS="--dev --ignore-platform-reqs" SYMFONY_DEPRECATIONS_HELPER=weak
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--dev"
    allow_failures:
        - php: hhvm-nightly

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction -v
    - composer info -D | sort
    - composer show twig/twig
    - ./vendor/bin/phpunit --version
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.13.1/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - phpenv config-rm xdebug.ini || return 0
    - ./vendor/bin/phpunit --verbose
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -vvv fix; fi
